name: setup-luau
description: GitHub action to install Luau; a scripting language derived from Lua.
author: ewd3v

inputs:
  version:
    description: "`Luau` git tag (usually in the form x.x)"
    required: false
  token:
    description: "GitHub token via `github.token`"
    default: "${{ github.token }}"
    required: false

runs:
  using: "composite"
  steps:
    - name: Change directory
      run: |
        mkdir -p "$HOME/.luau/bin"
        cd "$HOME/.luau/bin"
      shell: bash

    - name: Download Luau
      run: |
        case ${{ runner.os }} in
          Linux) pattern="*ubuntu.zip" ;;
          macOS) pattern="*macos.zip" ;;
          Windows) pattern="*windows.zip" ;;
        esac

        gh release download ${{ inputs.version }} --repo luau-lang/luau --pattern $pattern --output luau.zip
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      shell: bash

    - name: Unzip Luau
      run: |
        unzip luau.zip
      shell: bash

    - name: Delete artifacts
      run: |
        rm luau.zip
      shell: bash

    - name: Set environment variable
      if: runner.os == 'Windows'
      run: echo "$PWD" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: powershell

    - name: Set environment variable
      if: runner.os != 'Windows'
      run: echo "$PWD" >> $GITHUB_PATH
      shell: bash

branding:
  icon: moon
  color: blue
