name: test
on:
  workflow_dispatch:
  push:
    paths:
      - "**.yml"
  pull_request:
    paths:
      - "**.yml"

defaults:
  run:
    shell: bash

jobs:
  test:
    uses: ./.github/workflows/env.yml
